spring:
    datasource:
       name: dataSource
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: root
       password: a9530.A.
       url: jdbc:mysql://127.0.0.1:3306/cloud_wall?useUnicode=true&serverTimezone=GMT%2B8&useSSL=false
       druid:
         initial-size: 5
         min-idle: 5
         maxActive: 20
         # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
         maxWait: 60000
         numTestsPerEvictionRun: 3
         keepAlive: true
         # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
         timeBetweenEvictionRunsMillis: 120000
         # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
         minEvictableIdleTimeMillis: 600000
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: true
         testOnReturn: false
         removeAbandoned: true
         removeAbandonedTimeout: 300
    sqltoy:
        # \u8FD9\u91CC\u8981\u6CE8\u610F\uFF0C\u6307\u5B9Asql\u6587\u4EF6\u7684\u8DEF\u5F84,\u591A\u4E2A\u53EF\u4EE5\u7528\u9017\u53F7\u5206\u9694\uFF0C\u4F1A\u81EA\u52A8\u5411\u4E0B\u5BFB\u627E
        sqlResourcesDir: classpath:/
        # \u7F13\u5B58\u7FFB\u8BD1\u7684\u914D\u7F6E
        translateConfig: classpath:/sqltoy/sqltoy-translate.xml
        # debug\u6A21\u5F0F\u4F1A\u6253\u5370\u6267\u884Csql
        debug: true
        # \u63D0\u4F9B\u7EDF\u4E00\u5B57\u6BB5:createBy createTime updateBy updateTime \u7B49\u5B57\u6BB5\u8865\u6F0F\u6027(\u4E3A\u7A7A\u65F6)\u8D4B\u503C(\u53EF\u9009\u914D\u7F6E)
        unifyFieldsHandler: cn.cps.sqltoy.plugins.SqlToyUnifyFieldsHandler
        # sql\u6267\u884C\u8D85\u8FC7\u591A\u957F\u65F6\u95F4\u5219\u8FDB\u884C\u65E5\u5FD7\u8F93\u51FA,\u7528\u4E8E\u76D1\u63A7\u54EA\u4E9B\u6162sql(\u53EF\u9009\u914D\u7F6E:\u9ED8\u8BA430\u79D2)
        printSqlTimeoutMillis: 300000