spring:
    datasource:
       name: dataSource
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: root
       password: a9530.A.
       url: jdbc:mysql://127.0.0.1:3306/cloud_wall?useUnicode=true&serverTimezone=GMT%2B8&useSSL=false
       druid:
         initial-size: 5
         min-idle: 5
         maxActive: 20
         # 配置获取连接等待超时的时间
         maxWait: 60000
         numTestsPerEvictionRun: 3
         keepAlive: true
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         timeBetweenEvictionRunsMillis: 120000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
         minEvictableIdleTimeMillis: 600000
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: true
         testOnReturn: false
         removeAbandoned: true
         removeAbandonedTimeout: 300
    sqltoy:
        # 这里要注意，指定sql文件的路径,多个可以用逗号分隔，会自动向下寻找
        sqlResourcesDir: classpath:/
        # 缓存翻译的配置
        translateConfig: classpath:/sqltoy/sqltoy-translate.xml
        # debug模式会打印执行sql
        debug: true
        # 提供统一字段:createBy createTime updateBy updateTime 等字段补漏性(为空时)赋值(可选配置)
        unifyFieldsHandler: cn.cps.sqltoy.plugins.SqlToyUnifyFieldsHandler
        # sql执行超过多长时间则进行日志输出,用于监控哪些慢sql(可选配置:默认30秒)
        printSqlTimeoutMillis: 300000